version: '3.4'

services:
  db:
    container_name: RunGroupWebApplicationDB
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Express
    ports:
      - 1433:1433
  rungroupwebapp:
    container_name: RunGroupWebApplication
    image: ${DOCKER_REGISTRY-}rungroupwebapplications
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_CONNECTION_STRING=Server=db;Database=RunGroups;User=sa;Password=yourStrong(!)Password;Encrypt=false
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - db